# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include:
    - $

pr:
- master


pool:
  vmImage: Hosted Windows 2019 with VS2019

steps:
- powershell: |
   Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
   Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
   Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

   Import-Module "$(Build.SourcesDirectory)\PSAzureDevOps" -Force

  displayName: 'Install Pester and import module'

- powershell: |
   $Results = Invoke-Pester -PassThru

   if ($Results.FailedCount -ne "0"){
       Throw "a PesterTest has failed"
   }
   if ($Results.PassedCount -eq "0"){
       Throw "There was no passed PesterTest"
   }
  failOnStderr: true
  displayName: 'Invoke-Pester'

- task: PowerShell@2
  displayName: 'PSScriptanalyzer-tests'
  inputs:
    targetType: filePath
    filePath: Tests/PSScriptAnalyzer.ps1
    arguments: '-ScriptPath "$(Build.SourcesDirectory)\PSAzureDevOps\"'
    failOnStderr: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: PSAzureDevOps
