resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: azureps

#Your build pipeline references a secret variable named ‘LocalPassword’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘domainPW’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘wsKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
steps:
- powershell: |
   Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
   install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
  displayName: 'Install Pester'

- powershell: ./'Tests/Invoke-Pester.ps1'
  displayName: 'Basic Pester Test'

- task: AzureResourceGroupDeployment@2
  displayName: 'Azure Deployment Test'
  inputs:
    azureSubscription: 'OGD Algemeen (PAYG) (03d914ad-63f7-4fab-b24e-7b56e7da5a56)'

    resourceGroupName: BarbaratestArm

    location: 'West Europe'

    csmFile: Deploymentfiles/azuredeploy.json

    csmParametersFile: Deploymentfiles/azuredeploy.parameters.json

    overrideParameters: '-adminPassword "$(LocalPassword)" -domainPassword "$(domainPW)" -workspaceKey "$(wsKey)"'

    deploymentMode: Validation

    deploymentOutputs: Output


- task: AzurePowerShell@3
  displayName: 'Resource output'
  inputs:
    azureSubscription: 'OGD Algemeen (PAYG) (03d914ad-63f7-4fab-b24e-7b56e7da5a56)'

    ScriptPath: Tests/TestarmPS.ps1

    ScriptArguments: '-ResourceGroup "BarbaraTestArm" -TemplatePath "$(Build.SourcesDirectory)\Deploymentfiles\azuredeploy.json" -ParametersPath "$(Build.SourcesDirectory)\Deploymentfiles\azuredeploy.parameters.json" '

    azurePowerShellVersion: LatestVersion


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: Deploymentfiles



